import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

const indianStates = [
  'Delhi', 'Maharashtra', 'Karnataka', 'Tamil Nadu', 'Telangana',
  'Uttar Pradesh', 'West Bengal', 'Rajasthan', 'Gujarat', 'Madhya Pradesh',
  'Kerala', 'Punjab', 'Haryana', 'Odisha', 'Assam'
];

const collegeTypes = ['IIT', 'NIT', 'IIIT', 'Private', 'Government'];

const collegesData = [
  // IITs
  {
    name: 'Indian Institute of Technology Bombay',
    slug: 'iit-bombay',
    location: 'Powai',
    state: 'Maharashtra',
    fees: 220000,
    rating: 4.8,
    ranking: 1,
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&h=300&fit=crop',
    description: 'IIT Bombay is a public technical university located in Powai, Mumbai. Established in 1958, it is one of the premier engineering institutions in India, known for its rigorous academic programs and excellent placement records.',
    placementPercentage: 95,
    avgPackage: 2100000,
    establishedYear: 1958,
  },
  {
    name: 'Indian Institute of Technology Delhi',
    slug: 'iit-delhi',
    location: 'Hauz Khas',
    state: 'Delhi',
    fees: 225000,
    rating: 4.7,
    ranking: 2,
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&h=300&fit=crop',
    description: 'IIT Delhi is a public technical university located in Hauz Khas, New Delhi. Established in 1961, it is recognized as an Institute of National Importance and is one of the top engineering colleges in India.',
    placementPercentage: 94,
    avgPackage: 1950000,
    establishedYear: 1961,
  },
  {
    name: 'Indian Institute of Technology Madras',
    slug: 'iit-madras',
    location: 'Adyar',
    state: 'Tamil Nadu',
    fees: 215000,
    rating: 4.7,
    ranking: 3,
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&h=300&fit=crop',
    description: 'IIT Madras is a public technical university located in Chennai. Established in 1959, it has been consistently ranked as one of the best engineering institutions in India and Asia.',
    placementPercentage: 93,
    avgPackage: 1900000,
    establishedYear: 1959,
  },
  {
    name: 'Indian Institute of Technology Kanpur',
    slug: 'iit-kanpur',
    location: 'Kalyanpur',
    state: 'Uttar Pradesh',
    fees: 210000,
    rating: 4.6,
    ranking: 4,
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&h=300&fit=crop',
    description: 'IIT Kanpur is a public technical university located in Kanpur. Established in 1959, it is known for its strong focus on research and innovation in engineering and technology.',
    placementPercentage: 92,
    avgPackage: 1850000,
    establishedYear: 1959,
  },
  {
    name: 'Indian Institute of Technology Kharagpur',
    slug: 'iit-kharagpur',
    location: 'Kharagpur',
    state: 'West Bengal',
    fees: 205000,
    rating: 4.6,
    ranking: 5,
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&h=300&fit=crop',
    description: 'IIT Kharagpur is the first IIT established in 1951. It is an Institute of National Importance and has a sprawling 2100-acre campus with excellent infrastructure.',
    placementPercentage: 91,
    avgPackage: 1800000,
    establishedYear: 1951,
  },
  {
    name: 'Indian Institute of Technology Roorkee',
    slug: 'iit-roorkee',
    location: 'Roorkee',
    state: 'Uttarakhand',
    fees: 200000,
    rating: 4.5,
    ranking: 6,
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&h=300&fit=crop',
    description: 'IIT Roorkee, established in 1847, is the oldest engineering institution in Asia. It was converted into an IIT in 2001 and continues to be a premier technical university.',
    placementPercentage: 90,
    avgPackage: 1750000,
    establishedYear: 1847,
  },
  {
    name: 'Indian Institute of Technology Guwahati',
    slug: 'iit-guwahati',
    location: 'Guwahati',
    state: 'Assam',
    fees: 195000,
    rating: 4.5,
    ranking: 7,
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&h=300&fit=crop',
    description: 'IIT Guwahati is a public technical university located in Assam. Established in 1994, it has a beautiful 700-hectare campus on the banks of the Brahmaputra River.',
    placementPercentage: 89,
    avgPackage: 1700000,
    establishedYear: 1994,
  },
  {
    name: 'Indian Institute of Technology Hyderabad',
    slug: 'iit-hyderabad',
    location: 'Sangareddy',
    state: 'Telangana',
    fees: 220000,
    rating: 4.4,
    ranking: 8,
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&h=300&fit=crop',
    description: 'IIT Hyderabad is a public technical university established in 2008. It is known for its modern curriculum and strong industry connections.',
    placementPercentage: 88,
    avgPackage: 1650000,
    establishedYear: 2008,
  },
  // NITs
  {
    name: 'National Institute of Technology Trichy',
    slug: 'nit-trichy',
    location: 'Tiruchirappalli',
    state: 'Tamil Nadu',
    fees: 160000,
    rating: 4.4,
    ranking: 9,
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&h=300&fit=crop',
    description: 'NIT Trichy is one of the top NITs in India, established in 1964. It is known for its excellent academic programs and strong alumni network.',
    placementPercentage: 87,
    avgPackage: 1200000,
    establishedYear: 1964,
  },
  {
    name: 'National Institute of Technology Surathkal',
    slug: 'nit-surathkal',
    location: 'Surathkal',
    state: 'Karnataka',
    fees: 155000,
    rating: 4.3,
    ranking: 10,
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&h=300&fit=crop',
    description: 'NIT Surathkal, established in 1960, is located on the Arabian Sea coast. It is known for its beautiful campus and excellent engineering programs.',
    placementPercentage: 86,
    avgPackage: 1150000,
    establishedYear: 1960,
  },
  {
    name: 'National Institute of Technology Warangal',
    slug: 'nit-warangal',
    location: 'Warangal',
    state: 'Telangana',
    fees: 150000,
    rating: 4.3,
    ranking: 11,
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&h=300&fit=crop',
    description: 'NIT Warangal, established in 1959, is one of the premier engineering institutions in India. It has a sprawling 500-acre campus.',
    placementPercentage: 85,
    avgPackage: 1100000,
    establishedYear: 1959,
  },
  {
    name: 'National Institute of Technology Calicut',
    slug: 'nit-calicut',
    location: 'Kozhikode',
    state: 'Kerala',
    fees: 145000,
    rating: 4.2,
    ranking: 12,
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&h=300&fit=crop',
    description: 'NIT Calicut, established in 1961, is located in the scenic Malabar region of Kerala. It is known for its strong focus on research and development.',
    placementPercentage: 84,
    avgPackage: 1050000,
    establishedYear: 1961,
  },
  {
    name: 'National Institute of Technology Rourkela',
    slug: 'nit-rourkela',
    location: 'Rourkela',
    state: 'Odisha',
    fees: 148000,
    rating: 4.2,
    ranking: 13,
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&h=300&fit=crop',
    description: 'NIT Rourkela, established in 1961, is one of the first eight regional engineering colleges in India. It has excellent infrastructure and labs.',
    placementPercentage: 83,
    avgPackage: 1000000,
    establishedYear: 1961,
  },
  {
    name: 'National Institute of Technology Jaipur',
    slug: 'nit-jaipur',
    location: 'Jaipur',
    state: 'Rajasthan',
    fees: 142000,
    rating: 4.1,
    ranking: 14,
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&h=300&fit=crop',
    description: 'MNIT Jaipur, established in 1963, is a premier engineering institution in Rajasthan. It offers excellent programs in engineering and management.',
    placementPercentage: 82,
    avgPackage: 950000,
    establishedYear: 1963,
  },
  {
    name: 'National Institute of Technology Bhopal',
    slug: 'nit-bhopal',
    location: 'Bhopal',
    state: 'Madhya Pradesh',
    fees: 140000,
    rating: 4.1,
    ranking: 15,
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&h=300&fit=crop',
    description: 'NIT Bhopal, established in 1960, is located in the city of lakes. It has a green campus and offers quality engineering education.',
    placementPercentage: 81,
    avgPackage: 900000,
    establishedYear: 1960,
  },
  // IIITs
  {
    name: 'International Institute of Information Technology Hyderabad',
    slug: 'iiit-hyderabad',
    location: 'Gachibowli',
    state: 'Telangana',
    fees: 350000,
    rating: 4.5,
    ranking: 16,
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&h=300&fit=crop',
    description: 'IIIT Hyderabad is a premier institute for information technology education and research. It is known for its cutting-edge research in AI and ML.',
    placementPercentage: 95,
    avgPackage: 1800000,
    establishedYear: 1998,
  },
  {
    name: 'International Institute of Information Technology Bangalore',
    slug: 'iiit-bangalore',
    location: 'Electronic City',
    state: 'Karnataka',
    fees: 320000,
    rating: 4.3,
    ranking: 17,
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&h=300&fit=crop',
    description: 'IIIT Bangalore is a leading institute for IT education located in the heart of India\'s Silicon Valley. It has strong industry connections.',
    placementPercentage: 92,
    avgPackage: 1500000,
    establishedYear: 1999,
  },
  {
    name: 'International Institute of Information Technology Delhi',
    slug: 'iiit-delhi',
    location: 'Okhla',
    state: 'Delhi',
    fees: 310000,
    rating: 4.2,
    ranking: 18,
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&h=300&fit=crop',
    description: 'IIIT Delhi is a state university focused on IT education and research. It offers innovative programs and has excellent research facilities.',
    placementPercentage: 90,
    avgPackage: 1400000,
    establishedYear: 2007,
  },
  // Private Colleges
  {
    name: 'Birla Institute of Technology and Science Pilani',
    slug: 'bits-pilani',
    location: 'Pilani',
    state: 'Rajasthan',
    fees: 450000,
    rating: 4.5,
    ranking: 19,
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&h=300&fit=crop',
    description: 'BITS Pilani is a deemed university known for its rigorous academic programs and flexible curriculum. It has multiple campuses across India.',
    placementPercentage: 94,
    avgPackage: 1600000,
    establishedYear: 1964,
  },
  {
    name: 'Vellore Institute of Technology',
    slug: 'vit-vellore',
    location: 'Vellore',
    state: 'Tamil Nadu',
    fees: 200000,
    rating: 4.0,
    ranking: 20,
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&h=300&fit=crop',
    description: 'VIT Vellore is a private deemed university known for its large campus and diverse student community. It offers a wide range of engineering programs.',
    placementPercentage: 85,
    avgPackage: 750000,
    establishedYear: 1984,
  },
  {
    name: 'Manipal Institute of Technology',
    slug: 'mit-manipal',
    location: 'Manipal',
    state: 'Karnataka',
    fees: 330000,
    rating: 4.2,
    ranking: 21,
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&h=300&fit=crop',
    description: 'MIT Manipal is part of Manipal Academy of Higher Education. It is known for its excellent infrastructure and industry-oriented curriculum.',
    placementPercentage: 88,
    avgPackage: 900000,
    establishedYear: 1957,
  },
  {
    name: 'SRM Institute of Science and Technology',
    slug: 'srm-chennai',
    location: 'Chennai',
    state: 'Tamil Nadu',
    fees: 250000,
    rating: 3.9,
    ranking: 22,
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&h=300&fit=crop',
    description: 'SRM Institute is a private deemed university with a massive campus. It offers a wide range of programs and has strong industry partnerships.',
    placementPercentage: 82,
    avgPackage: 650000,
    establishedYear: 1985,
  },
  {
    name: 'Thapar Institute of Engineering and Technology',
    slug: 'thapar-patiala',
    location: 'Patiala',
    state: 'Punjab',
    fees: 350000,
    rating: 4.1,
    ranking: 23,
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&h=300&fit=crop',
    description: 'Thapar Institute is a deemed university known for its quality education and excellent placement records. It has a beautiful green campus.',
    placementPercentage: 86,
    avgPackage: 850000,
    establishedYear: 1956,
  },
  {
    name: 'Delhi Technological University',
    slug: 'dtu-delhi',
    location: 'Rohini',
    state: 'Delhi',
    fees: 180000,
    rating: 4.2,
    ranking: 24,
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&h=300&fit=crop',
    description: 'DTU, formerly Delhi College of Engineering, is a state university known for its excellent engineering programs and prime location in Delhi.',
    placementPercentage: 88,
    avgPackage: 1100000,
    establishedYear: 1941,
  },
  {
    name: 'Netaji Subhas University of Technology',
    slug: 'nsut-delhi',
    location: 'Dwarka',
    state: 'Delhi',
    fees: 175000,
    rating: 4.1,
    ranking: 25,
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&h=300&fit=crop',
    description: 'NSUT, formerly NSIT, is a state university known for its focus on technology and innovation. It has excellent placement records.',
    placementPercentage: 87,
    avgPackage: 1050000,
    establishedYear: 1983,
  },
  {
    name: 'Jadavpur University',
    slug: 'jadavpur-kolkata',
    location: 'Kolkata',
    state: 'West Bengal',
    fees: 12000,
    rating: 4.3,
    ranking: 26,
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&h=300&fit=crop',
    description: 'Jadavpur University is a public university known for its extremely affordable fees and excellent education. It has a rich history and strong alumni network.',
    placementPercentage: 84,
    avgPackage: 800000,
    establishedYear: 1955,
  },
  {
    name: 'College of Engineering Pune',
    slug: 'coep-pune',
    location: 'Pune',
    state: 'Maharashtra',
    fees: 85000,
    rating: 4.0,
    ranking: 27,
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&h=300&fit=crop',
    description: 'COEP is one of the oldest engineering colleges in Asia, established in 1854. It has a rich legacy and excellent industry connections.',
    placementPercentage: 83,
    avgPackage: 750000,
    establishedYear: 1854,
  },
  {
    name: 'Indian Institute of Information Technology Allahabad',
    slug: 'iiit-allahabad',
    location: 'Prayagraj',
    state: 'Uttar Pradesh',
    fees: 280000,
    rating: 4.2,
    ranking: 28,
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&h=300&fit=crop',
    description: 'IIIT Allahabad is one of the first IIITs established in India. It is known for its strong focus on IT education and research.',
    placementPercentage: 89,
    avgPackage: 1200000,
    establishedYear: 1999,
  },
  {
    name: 'PES University',
    slug: 'pes-bangalore',
    location: 'Bangalore',
    state: 'Karnataka',
    fees: 300000,
    rating: 4.0,
    ranking: 29,
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&h=300&fit=crop',
    description: 'PES University is a private university in Bangalore known for its quality education and excellent placement opportunities in the IT sector.',
    placementPercentage: 85,
    avgPackage: 800000,
    establishedYear: 2013,
  },
  {
    name: 'RV College of Engineering',
    slug: 'rvce-bangalore',
    location: 'Bangalore',
    state: 'Karnataka',
    fees: 120000,
    rating: 4.1,
    ranking: 30,
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&h=300&fit=crop',
    description: 'RVCE is one of the top private engineering colleges in Karnataka. It has excellent infrastructure and strong industry connections.',
    placementPercentage: 86,
    avgPackage: 850000,
    establishedYear: 1963,
  },
  {
    name: 'PSG College of Technology',
    slug: 'psg-coimbatore',
    location: 'Coimbatore',
    state: 'Tamil Nadu',
    fees: 55000,
    rating: 4.0,
    ranking: 31,
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&h=300&fit=crop',
    description: 'PSG Tech is a government-aided institution known for its quality education at affordable fees. It has a strong alumni network.',
    placementPercentage: 84,
    avgPackage: 700000,
    establishedYear: 1951,
  },
  {
    name: 'Amity University',
    slug: 'amity-noida',
    location: 'Noida',
    state: 'Uttar Pradesh',
    fees: 350000,
    rating: 3.8,
    ranking: 32,
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&h=300&fit=crop',
    description: 'Amity University is a private university with a sprawling campus in Noida. It offers a wide range of programs and has modern infrastructure.',
    placementPercentage: 80,
    avgPackage: 600000,
    establishedYear: 2005,
  },
  {
    name: 'LPU - Lovely Professional University',
    slug: 'lpu-jalandhar',
    location: 'Jalandhar',
    state: 'Punjab',
    fees: 180000,
    rating: 3.7,
    ranking: 33,
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&h=300&fit=crop',
    description: 'LPU is one of the largest private universities in India with a massive campus. It offers diverse programs and has a focus on practical learning.',
    placementPercentage: 78,
    avgPackage: 550000,
    establishedYear: 2006,
  },
  {
    name: 'Kalinga Institute of Industrial Technology',
    slug: 'kiit-bhubaneswar',
    location: 'Bhubaneswar',
    state: 'Odisha',
    fees: 280000,
    rating: 3.9,
    ranking: 34,
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&h=300&fit=crop',
    description: 'KIIT is a deemed university known for its large campus and diverse student community from across India and abroad.',
    placementPercentage: 81,
    avgPackage: 650000,
    establishedYear: 1992,
  },
  {
    name: 'SASTRA Deemed University',
    slug: 'sastra-thanjavur',
    location: 'Thanjavur',
    state: 'Tamil Nadu',
    fees: 220000,
    rating: 4.0,
    ranking: 35,
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&h=300&fit=crop',
    description: 'SASTRA is a deemed university known for its academic excellence and research focus. It has produced many successful engineers and entrepreneurs.',
    placementPercentage: 83,
    avgPackage: 700000,
    establishedYear: 1984,
  },
  {
    name: 'NIT Hamirpur',
    slug: 'nit-hamirpur',
    location: 'Hamirpur',
    state: 'Himachal Pradesh',
    fees: 145000,
    rating: 4.0,
    ranking: 36,
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&h=300&fit=crop',
    description: 'NIT Hamirpur is located in the scenic hills of Himachal Pradesh. It offers quality engineering education in a peaceful environment.',
    placementPercentage: 80,
    avgPackage: 850000,
    establishedYear: 1986,
  },
  {
    name: 'NIT Kurukshetra',
    slug: 'nit-kurukshetra',
    location: 'Kurukshetra',
    state: 'Haryana',
    fees: 155000,
    rating: 4.0,
    ranking: 37,
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&h=300&fit=crop',
    description: 'NIT Kurukshetra is one of the oldest NITs, established in 1963. It has excellent infrastructure and strong industry connections.',
    placementPercentage: 82,
    avgPackage: 900000,
    establishedYear: 1963,
  },
  {
    name: 'NIT Durgapur',
    slug: 'nit-durgapur',
    location: 'Durgapur',
    state: 'West Bengal',
    fees: 150000,
    rating: 4.0,
    ranking: 38,
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&h=300&fit=crop',
    description: 'NIT Durgapur, established in 1960, is one of the premier engineering institutions in Eastern India with excellent academic programs.',
    placementPercentage: 81,
    avgPackage: 850000,
    establishedYear: 1960,
  },
  {
    name: 'NIT Nagpur',
    slug: 'nit-nagpur',
    location: 'Nagpur',
    state: 'Maharashtra',
    fees: 148000,
    rating: 3.9,
    ranking: 39,
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&h=300&fit=crop',
    description: 'VNIT Nagpur, established in 1960, is one of the oldest NITs. It has a beautiful campus and offers quality engineering education.',
    placementPercentage: 80,
    avgPackage: 800000,
    establishedYear: 1960,
  },
  {
    name: 'NIT Silchar',
    slug: 'nit-silchar',
    location: 'Silchar',
    state: 'Assam',
    fees: 140000,
    rating: 3.9,
    ranking: 40,
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&h=300&fit=crop',
    description: 'NIT Silchar is one of the oldest NITs in Northeast India. It offers quality education and has a diverse student community.',
    placementPercentage: 79,
    avgPackage: 750000,
    establishedYear: 1967,
  },
  {
    name: 'IIITDM Jabalpur',
    slug: 'iiitdm-jabalpur',
    location: 'Jabalpur',
    state: 'Madhya Pradesh',
    fees: 250000,
    rating: 3.9,
    ranking: 41,
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&h=300&fit=crop',
    description: 'IIITDM Jabalpur is focused on design and manufacturing education. It offers unique programs combining IT with design thinking.',
    placementPercentage: 82,
    avgPackage: 900000,
    establishedYear: 2005,
  },
  {
    name: 'IIITDM Kancheepuram',
    slug: 'iiitdm-kancheepuram',
    location: 'Kancheepuram',
    state: 'Tamil Nadu',
    fees: 240000,
    rating: 3.8,
    ranking: 42,
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&h=300&fit=crop',
    description: 'IIITDM Kancheepuram is an IIIT focused on design and manufacturing. It is located near Chennai and has good industry connections.',
    placementPercentage: 80,
    avgPackage: 850000,
    establishedYear: 2007,
  },
  {
    name: 'IIIT Gwalior',
    slug: 'iiit-gwalior',
    location: 'Gwalior',
    state: 'Madhya Pradesh',
    fees: 230000,
    rating: 3.8,
    ranking: 43,
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&h=300&fit=crop',
    description: 'IIIT Gwalior is a state-private university focused on information technology education. It has modern infrastructure and good placement records.',
    placementPercentage: 79,
    avgPackage: 800000,
    establishedYear: 2001,
  },
  {
    name: 'IIIT Lucknow',
    slug: 'iiit-lucknow',
    location: 'Lucknow',
    state: 'Uttar Pradesh',
    fees: 260000,
    rating: 4.0,
    ranking: 44,
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&h=300&fit=crop',
    description: 'IIIT Lucknow is a premier institute for IT education in Uttar Pradesh. It has excellent research facilities and industry partnerships.',
    placementPercentage: 85,
    avgPackage: 1100000,
    establishedYear: 2001,
  },
  {
    name: 'IIIT Pune',
    slug: 'iiit-pune',
    location: 'Pune',
    state: 'Maharashtra',
    fees: 280000,
    rating: 3.9,
    ranking: 45,
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&h=300&fit=crop',
    description: 'IIIT Pune is an autonomous institute focused on IT education and research. It is located in the educational hub of Pune.',
    placementPercentage: 83,
    avgPackage: 950000,
    establishedYear: 2013,
  },
];

const coursesData = [
  { name: 'Computer Science and Engineering', duration: '4 Years', degree: 'B.Tech' },
  { name: 'Electronics and Communication Engineering', duration: '4 Years', degree: 'B.Tech' },
  { name: 'Mechanical Engineering', duration: '4 Years', degree: 'B.Tech' },
  { name: 'Electrical Engineering', duration: '4 Years', degree: 'B.Tech' },
  { name: 'Civil Engineering', duration: '4 Years', degree: 'B.Tech' },
  { name: 'Information Technology', duration: '4 Years', degree: 'B.Tech' },
  { name: 'Artificial Intelligence and Machine Learning', duration: '4 Years', degree: 'B.Tech' },
  { name: 'Data Science and Engineering', duration: '4 Years', degree: 'B.Tech' },
  { name: 'Chemical Engineering', duration: '4 Years', degree: 'B.Tech' },
  { name: 'Aerospace Engineering', duration: '4 Years', degree: 'B.Tech' },
  { name: 'Biotechnology', duration: '4 Years', degree: 'B.Tech' },
  { name: 'Mathematics and Computing', duration: '4 Years', degree: 'B.Tech' },
  { name: 'Computer Science and Engineering', duration: '2 Years', degree: 'M.Tech' },
  { name: 'Data Science', duration: '2 Years', degree: 'M.Sc' },
  { name: 'Business Administration', duration: '2 Years', degree: 'MBA' },
];

const reviewsData = [
  { userName: 'Rahul Sharma', rating: 5, comment: 'Excellent infrastructure and faculty. The placement opportunities are amazing. Got placed in a top tech company with a great package.' },
  { userName: 'Priya Patel', rating: 4, comment: 'Great academic environment and research opportunities. Campus life is vibrant with many technical and cultural fests.' },
  { userName: 'Arjun Reddy', rating: 5, comment: 'One of the best decisions of my life. The peer group is excellent and the alumni network is very strong.' },
  { userName: 'Sneha Gupta', rating: 4, comment: 'Good balance of academics and extracurricular activities. The coding culture here is exceptional.' },
  { userName: 'Vikram Singh', rating: 5, comment: 'World-class labs and research facilities. Professors are very supportive and encouraging.' },
  { userName: 'Ananya Iyer', rating: 4, comment: 'The campus is beautiful and well-maintained. Hostel facilities are good. Food quality could be improved.' },
  { userName: 'Rohan Mehta', rating: 5, comment: 'Amazing placement record. Companies like Google, Microsoft, Amazon visit the campus regularly.' },
  { userName: 'Kavya Nair', rating: 4, comment: 'Strong focus on practical learning and projects. The internship opportunities are excellent.' },
  { userName: 'Aditya Kumar', rating: 5, comment: 'Best engineering college in India. The brand value alone opens many doors for career growth.' },
  { userName: 'Divya Krishnan', rating: 4, comment: 'Great exposure to cutting-edge technology and research. The startup ecosystem is thriving.' },
];

async function main() {
  console.log('🌱 Starting database seeding...');

  // Clear existing data
  await prisma.savedCollege.deleteMany();
  await prisma.review.deleteMany();
  await prisma.course.deleteMany();
  await prisma.college.deleteMany();
  await prisma.user.deleteMany();

  console.log('🗑️  Cleared existing data');

  // Create a demo user
  const hashedPassword = await bcrypt.hash('demo123', 12);
  await prisma.user.create({
    data: {
      name: 'Demo User',
      email: 'demo@collegefinder.com',
      password: hashedPassword,
    },
  });

  console.log('👤 Created demo user');

  // Create colleges with courses and reviews
  for (const college of collegesData) {
    const createdCollege = await prisma.college.create({
      data: {
        name: college.name,
        slug: college.slug,
        location: college.location,
        state: college.state,
        fees: college.fees,
        rating: college.rating,
        ranking: college.ranking,
        image: college.image,
        description: college.description,
        placementPercentage: college.placementPercentage,
        avgPackage: college.avgPackage,
        establishedYear: college.establishedYear,
      },
    });

    // Add courses to each college (randomly select 5-8 courses)
    const numCourses = 5 + Math.floor(Math.random() * 4);
    const shuffledCourses = [...coursesData].sort(() => 0.5 - Math.random());
    const selectedCourses = shuffledCourses.slice(0, numCourses);

    for (const course of selectedCourses) {
      const courseFees = college.fees * (course.degree === 'B.Tech' ? 1 : course.degree === 'M.Tech' ? 0.8 : 0.6);
      await prisma.course.create({
        data: {
          name: course.name,
          duration: course.duration,
          degree: course.degree,
          fees: Math.round(courseFees),
          collegeId: createdCollege.id,
        },
      });
    }

    // Add reviews to each college (randomly select 2-4 reviews)
    const numReviews = 2 + Math.floor(Math.random() * 3);
    const shuffledReviews = [...reviewsData].sort(() => 0.5 - Math.random());
    const selectedReviews = shuffledReviews.slice(0, numReviews);

    for (const review of selectedReviews) {
      await prisma.review.create({
        data: {
          userName: review.userName,
          rating: review.rating,
          comment: review.comment,
          collegeId: createdCollege.id,
        },
      });
    }

    console.log(`✅ Created college: ${college.name}`);
  }

  console.log('🎉 Database seeding completed successfully!');
  console.log(`📊 Total colleges: ${collegesData.length}`);
  console.log(`📊 Total courses per college: 5-8`);
  console.log(`📊 Total reviews per college: 2-4`);
}

main()
  .catch((e) => {
    console.error('❌ Error during seeding:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });